# Couchbase Server testing image; SSH needs to be enabled
# for QE's testing framework

# This is a RHEL 7 image from Redhat
FROM registry.access.redhat.com/rhel7

MAINTAINER Couchbase Docker Team <docker@couchbase.com>


RUN yum repolist --disablerepo="*" && \
    yum-config-manager --enable rhel-7-server-rpms rhel-7-server-rt-rpms && \
    yum-config-manager --enable rhel-7-server-optional-rpms \
        rhel-7-server-extras-rpms rhel-server-rhscl-7-rpms && \
    yum -y --disablerepo=rhel-7-server-rt-beta-rpms update-minimal --security \
        --sec-severity=Important --sec-severity=Critical --setopt=tsflags=nodocs

# Install yum dependencies
RUN yum -y --disablerepo=rhel-7-server-rt-beta-rpms install tar \
    && yum clean all && \
      yum -y --disablerepo=rhel-7-server-rt-beta-rpms install openssl openssh openssh-server \
      lsof lshw net-tools numactl python-httplib2 \
      sysstati wget screen psmisc zip unzip \
      gzip

# Set up for SSH daemon
RUN sed -ri 's/UsePAM yes/#UsePAM yes/g' /etc/ssh/sshd_config && \
    sed -ri 's/#UsePAM no/UsePAM no/g' /etc/ssh/sshd_config && \
    ssh-keygen -f /etc/ssh/ssh_host_rsa_key -N '' -t rsa && \
    ssh-keygen -f /etc/ssh/ssh_host_dsa_key -N '' -t dsa

# Install runit
RUN curl -s https://packagecloud.io/install/repositories/imeyer/runit/script.rpm.sh | bash
RUN yum -y --disablerepo=rhel-7-server-rt-beta-rpms install runit

COPY functions /etc/init.d/

# Add licenses and help file
COPY licenses /licenses
COPY help.1 /help.1

ARG PROD_VERSION
ARG CB_RELEASE_URL=http://packages.couchbase.com/releases
ARG CB_PACKAGE=couchbase-server-enterprise-${PROD_VERSION}-centos7.x86_64.rpm

ENV PATH=$PATH:/opt/couchbase/bin:/opt/couchbase/bin/tools:/opt/couchbase/bin/install

# Create Couchbase user with UID 1000 (necessary to match default
# boot2docker UID)
RUN groupadd -g1000 couchbase && \
    useradd couchbase -g couchbase -u1000 -m -s /bin/bash && \
    echo 'couchbase:couchbase' | chpasswd

# Install couchbase
RUN rpm --install $CB_RELEASE_URL/$PROD_VERSION/$CB_PACKAGE

# Add runit script for couchbase-server
COPY scripts/run /etc/service/couchbase-server/run

# Add dummy script for commands invoked by cbcollect_info that
# make no sense in a Docker container
COPY scripts/dummy.sh /usr/local/bin/
RUN ln -s dummy.sh /usr/local/bin/iptables-save && \
    ln -s dummy.sh /usr/local/bin/lvdisplay && \
    ln -s dummy.sh /usr/local/bin/vgdisplay && \
    ln -s dummy.sh /usr/local/bin/pvdisplay

# Clean the cache
RUN yum clean all

# Get the SSH daemon running
RUN mkdir /var/run/sshd && \
    echo 'root:couchbase' | chpasswd && \
    sed -i 's/PermitRootLogin without-password/PermitRootLogin yes/' /etc/ssh/sshd_config && \
    sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/sshd && \
    echo "export VISIBLE=now" >> /etc/profile

LABEL name="rhel7/couchbase-server"
LABEL vendor="Couchbase"
LABEL version="${PROD_VERSION}"
LABEL release="Latest"
LABEL summary="Couchbase Server ${PROD_VERSION} Enterprise"
LABEL description="Couchbase Server ${PROD_VERSION} Enterprise"
LABEL architecture="x86_64"
LABEL run="docker run -d --privileged -p 8091:8091 --restart always \
    --name NAME IMAGE"

COPY scripts/entrypoint-testing.sh /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
CMD ["couchbase-server"]

EXPOSE 22 8091 8092 8093 8094 9100 9101 9102 9103 9104 9105 9998 9999 11207 11210 11211 18091 18092 18093
VOLUME /opt/couchbase/var
